export interface MacroEvent {
  date: string        // YYYY-MM-DD
  title: string
  description: string
  impact: 'high' | 'medium' | 'low'
  assets: string[]    // keys: dxy | btc | brent | gold | sp500
  type: 'past' | 'upcoming'
  url?: string        // link to official source or news coverage
  beat?: string       // market impact if data beats expectations
  miss?: string       // market impact if data misses expectations
  outcome?: 'beat' | 'miss'  // auto-detected for past events with actual vs estimate data
  source?: 'news'    // present only on auto-fetched GDELT news events
}

// ─── Past Events ──────────────────────────────────────────────────────────────
// To annotate an event's outcome, add:  outcome: 'beat'  or  outcome: 'miss'
export const PAST_EVENTS: MacroEvent[] = [
  {
    date: '2024-09-18',
    title: 'Fed 首次降息 50bp',
    description: '自2020年以来首次降息，幅度超预期50bp，降至4.75-5.0%。黄金创历史新高，美元走弱，比特币同步上涨。',
    impact: 'high',
    assets: ['dxy', 'gold', 'sp500', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    beat: '降幅超预期（50bp vs 市场预期25bp）→ DXY↓，黄金创新高，美股+BTC走强',
    miss: '降幅不及预期或按兵不动 → DXY↑，金价承压，市场失望',
    outcome: 'beat',
  },
  {
    date: '2024-10-07',
    title: '中东局势升级，以黎冲突扩大',
    description: '以色列对黎巴嫩真主党展开大规模地面行动，中东紧张局势骤升。布伦特原油单日涨超4%，黄金避险需求攀升至2700美元/盎司上方。',
    impact: 'high',
    assets: ['brent', 'gold', 'dxy'],
    type: 'past',
    url: 'https://www.bbc.com/news/world/middle_east',
  },
  {
    date: '2024-11-05',
    title: '美国总统大选：特朗普胜选',
    description: '特朗普赢得2024年美国总统大选。市场迅速定价"特朗普交易"：美元指数飙升至104+，比特币突破75,000美元，黄金短暂承压，美股科技板块大涨。',
    impact: 'high',
    assets: ['dxy', 'btc', 'gold', 'sp500'],
    type: 'past',
    url: 'https://www.reuters.com/world/us/',
  },
  {
    date: '2024-11-07',
    title: 'Fed 降息 25bp（美国大选后）',
    description: '特朗普赢得大选后首次FOMC会议，降息25bp至4.5-4.75%。美元因"特朗普交易"强势，金价短暂承压。',
    impact: 'high',
    assets: ['dxy', 'gold', 'sp500', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2024-12-05',
    title: 'OPEC+ 延长减产至 2026 年中',
    description: 'OPEC+会议决定将日均减产220万桶的协议延长至2026年6月，并推迟原定增产计划。布伦特原油因过剩担忧仍承压，市场反应偏负面。',
    impact: 'medium',
    assets: ['brent', 'dxy'],
    type: 'past',
    url: 'https://www.opec.org/opec_web/en/press_room/press_releases.htm',
    beat: '维持/深化减产 → 布伦特反弹，能源股走强',
    miss: '延产决定未能提振市场，过剩担忧压制油价 → 布伦特承压，市场反应负面',
    outcome: 'miss',
  },
  {
    date: '2024-12-18',
    title: 'Fed 降息 25bp，点阵图超鹰',
    description: '降息至4.25-4.5%，但2025年降息预期从4次压缩至2次，市场大幅下跌。DXY创2022年来高点。',
    impact: 'high',
    assets: ['dxy', 'gold', 'sp500', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    beat: '鸽派点阵图/多次降息预期 → DXY↓，黄金+美股走强',
    miss: '点阵图鹰派超预期，2025降息次数大幅压缩 → DXY↑创新高，美股+金价大跌',
    outcome: 'miss',
  },
  {
    date: '2025-01-20',
    title: '特朗普就职，签署关税行政令',
    description: '特朗普宣誓就职，当天签署多项行政令，包括对加拿大、墨西哥加征25%关税意向及对中国加征10%关税的计划。美元指数短暂冲高，能源股上涨。',
    impact: 'high',
    assets: ['dxy', 'brent', 'gold', 'sp500'],
    type: 'past',
    url: 'https://www.whitehouse.gov/briefing-room/',
  },
  {
    date: '2025-01-29',
    title: 'Fed 暂停降息',
    description: '通胀数据反复，Fed按兵不动。鲍威尔表示"不急于调整政策"，市场对2025年降息次数分歧加大。',
    impact: 'high',
    assets: ['dxy', 'sp500'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-03-19',
    title: 'FOMC 会议 — 维持不变',
    description: '经济展望调降，点阵图仍显示2次降息预期。关税政策不确定性使得Fed措辞更加谨慎。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-04-02',
    title: '美国"对等关税"宣布',
    description: '特朗普宣布大规模对等关税，市场剧烈波动。原油因衰退预期暴跌，黄金一度创历史新高，美股单日跌幅为2020年来最大。',
    impact: 'high',
    assets: ['dxy', 'brent', 'gold', 'sp500', 'btc'],
    type: 'past',
    url: 'https://ustr.gov/',
    beat: '税率低于预期或排除关键品类 → 市场松一口气，美股+风险资产反弹',
    miss: '税率超预期，覆盖范围极广 → 衰退恐慌，美股单日跌幅创2020年来最大，油价暴跌',
    outcome: 'miss',
  },
  {
    date: '2025-04-09',
    title: '对等关税 90 天暂停（除中国外）',
    description: '特朗普宣布对大多数国家的对等关税暂停90天，但对中国税率上调至145%。美股单日涨幅超9%，黄金冲高，比特币强势反弹，原油从底部拉升。',
    impact: 'high',
    assets: ['dxy', 'brent', 'gold', 'sp500', 'btc'],
    type: 'past',
    url: 'https://ustr.gov/',
    beat: '暂停关税/谈判积极信号 → 美股单日涨超9%，BTC+黄金+布伦特齐涨，恐慌情绪骤降',
    miss: '关税全面升级/谈判破裂 → 全球风险资产继续下行',
    outcome: 'beat',
  },
  {
    date: '2025-05-07',
    title: 'FOMC 会议 — 维持不变',
    description: '关税不确定性下Fed继续观望。声明措辞强调"双重风险"（衰退 + 通胀）。',
    impact: 'high',
    assets: ['dxy', 'sp500'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-05-12',
    title: '美中贸易停火：关税从145%降至30%',
    description: '日内瓦美中贸易谈判达成协议，双方互降关税90天——美国对华税率从145%降至30%，中国对美从125%降至10%。全球风险资产大幅反弹。',
    impact: 'high',
    assets: ['dxy', 'brent', 'gold', 'sp500', 'btc'],
    type: 'past',
    url: 'https://ustr.gov/',
    beat: '协议幅度超预期，关税大幅削减 → 全球风险资产强势反弹，BTC+美股+布伦特齐升',
    miss: '谈判无实质进展 → 关税战持续，市场承压',
    outcome: 'beat',
  },
  {
    date: '2025-06-18',
    title: 'FOMC 会议 — 维持不变',
    description: '通胀略有回落但就业市场仍具韧性，Fed维持4.25-4.5%。市场预期年内降息窗口推迟至9月。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-07-30',
    title: 'FOMC 利率决议（7月）',
    description: '美联储7月议息会议。市场关注下半年降息节奏与措辞变化。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-09-17',
    title: 'FOMC 利率决议 + 点阵图（9月）',
    description: '附季度经济预测（SEP）。点阵图对2025下半年及2026年的降息路径指引是跨资产关注焦点。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-10-29',
    title: 'FOMC 利率决议（10月）',
    description: '美联储10月议息会议。临近年末，政策措辞对风险资产年末走势影响较大。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2025-12-10',
    title: 'FOMC 利率决议 + 点阵图（12月）',
    description: '年末会议，同步发布季度经济预测，为2026年货币政策路径定基调。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2026-01-28',
    title: 'FOMC 利率决议 — 维持不变',
    description: '2026年首次议息会议。Fed维持利率不变，强调将依赖数据决策，市场关注全年降息路径指引。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2026-03-18',
    title: 'FOMC 利率决议 + 点阵图',
    description: '附带季度经济预测（SEP）。点阵图显示的2026年降息次数指引引发跨资产波动。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2026-04-29',
    title: 'FOMC 利率决议 — 维持不变',
    description: '关税与通胀的不确定性使Fed继续观望。鲍威尔发布会措辞偏中性，风险资产震荡。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
  {
    date: '2026-06-17',
    title: 'FOMC 利率决议 + 点阵图',
    description: '年中议息会议，同步更新经济预测。是上半年最重要的政策节点，跨资产普遍出现异动。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent', 'btc'],
    type: 'past',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
  },
]

// ─── Upcoming Events ──────────────────────────────────────────────────────────
export const UPCOMING_EVENTS: MacroEvent[] = [
  {
    date: '2026-07-14',
    title: '美国 CPI 数据（6月）',
    description: '6月通胀数据。是否持续回落决定7月FOMC的态度。目前市场预期年化核心CPI约2.7%。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'upcoming',
    url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    beat: 'CPI高于预期（通胀顽固）→ DXY↑，金价承压，美股回落，9月降息概率骤降',
    miss: 'CPI低于预期（通胀降温）→ DXY↓，黄金+美股走强，9月降息概率升温',
  },
  {
    date: '2026-07-30',
    title: 'FOMC 利率决议',
    description: '7月会议。市场目前预计按兵不动，关键看CPI和就业数据是否支持重启降息。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent'],
    type: 'upcoming',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    beat: '鸽派惊喜/降息落地 → DXY↓，黄金+美股+BTC齐升，风险偏好回暖',
    miss: '继续按兵不动+措辞偏鹰 → DXY↑，金价承压，美股震荡，降息预期再延后',
  },
  {
    date: '2026-08-13',
    title: '美国 CPI 数据（7月）',
    description: '7月通胀数据。Jackson Hole 前最后一个重要宏观数据，对鲍威尔讲话基调影响大。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'upcoming',
    url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    beat: 'CPI超预期 → DXY↑，鲍威尔讲话或偏鹰，金价+美股承压',
    miss: '通胀继续降温 → DXY↓，黄金+美股走强，Jackson Hole鸽派预期升温',
  },
  {
    date: '2026-08-21',
    title: 'Jackson Hole 全球央行年会',
    description: '美联储主席鲍威尔在怀俄明州的讲话通常为下半年政策定基调。历史上多次出现市场异动。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'btc'],
    type: 'upcoming',
    url: 'https://www.kansascityfed.org/research/jackson-hole-economic-symposium/',
    beat: '鲍威尔明确降息信号 → DXY大跌，黄金+美股+BTC飙升，全球风险偏好提振',
    miss: '措辞审慎，不给降息承诺 → DXY↑，黄金震荡，美股回调，市场失望',
  },
  {
    date: '2026-09-11',
    title: '美国 CPI 数据（8月）',
    description: '9月FOMC前最后一个通胀数据，直接影响是否降息25bp的概率定价。',
    impact: 'medium',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'upcoming',
    url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    beat: 'CPI再超预期 → DXY↑，9月降息概率骤降至<25%，美股+金价承压',
    miss: '通胀继续走低 → DXY↓，9月降息几乎锁定，金价+美股强势',
  },
  {
    date: '2026-09-17',
    title: 'FOMC 利率决议',
    description: '"活跃会议"：降息还是继续暂停取决于夏季数据。市场目前隐含约50%降息概率。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent', 'btc'],
    type: 'upcoming',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    beat: '降息25bp落地 → DXY↓，黄金+美股+BTC涨，风险资产全面走强',
    miss: '继续暂停/措辞强硬 → DXY↑，金价小幅承压，美股震荡调整',
  },
  {
    date: '2026-10-14',
    title: 'OPEC+ 产量政策审议',
    description: 'OPEC+定期部长级会议，审议2026年H2产量配额。若全球需求走软，增产推迟可能支撑油价；若决定放量，布伦特或再次承压。',
    impact: 'medium',
    assets: ['brent', 'dxy'],
    type: 'upcoming',
    url: 'https://www.opec.org/opec_web/en/press_room/press_releases.htm',
    beat: '推迟增产/维持减产 → 布伦特反弹，能源股走强，通胀预期小升',
    miss: '宣布放量增产 → 布伦特下跌，能源股承压，通胀预期降温利于降息',
  },
  {
    date: '2026-10-29',
    title: 'FOMC 利率决议',
    description: '10月会议。历史上美联储在选举年前后决策更保守，市场波动性通常在此前后上升。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold'],
    type: 'upcoming',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    beat: '再次降息或明确鸽派信号 → DXY↓，风险资产全线走强',
    miss: '措辞谨慎/暂停 → DXY↑，市场情绪偏弱，年末走势存疑',
  },
  {
    date: '2026-11-01',
    title: '美中关税停火协议到期审议',
    description: '2025年5月日内瓦协议规定的90+180天停火窗口接近尾声。双方是否续签、调整税率将决定全球贸易预期与风险资产走向。',
    impact: 'high',
    assets: ['dxy', 'brent', 'gold', 'sp500', 'btc'],
    type: 'upcoming',
    url: 'https://ustr.gov/',
    beat: '续签协议/进一步降税 → 全球风险资产走强，BTC+美股+布伦特反弹，DXY承压',
    miss: '谈判破裂/加税 → 黄金避险大涨，美股+BTC下跌，贸易战预期重燃',
  },
  {
    date: '2026-12-10',
    title: 'FOMC 利率决议 + SEP 经济预测',
    description: '年末会议，同步发布季度经济预测（点阵图）。将定调2027年降息路径，是全年最重要的FOMC之一。',
    impact: 'high',
    assets: ['dxy', 'sp500', 'gold', 'brent', 'btc'],
    type: 'upcoming',
    url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    beat: '降息+点阵图显示2027年多次降息 → DXY持续下行，黄金+美股强势收官',
    miss: '维持不变+鹰派点阵图 → DXY↑，年末风险资产普遍回调',
  },
]
